server:
  port: 9999

spring:
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: keycloak
            client-id: gateway
            client-secret: d40a26a3-2eaf-4597-8cf5-e023364ea028
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,profile,email,user,admin
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/oauth2-demo
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
