server:
  port: 9001

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/auth/realms/oauth2-demo/protocol/openid-connect/certs
  application:
    name: resource-server-b

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: oauth2-demo
  resource: client-credentials
  public-client: false